name: Generate Snake Animation

on:
  schedule:
    - cron: "45 23 * * *" # todos los días a las 23:45 UTC
  workflow_dispatch: # permite correrlo manualmente desde Actions

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake game from GitHub contributions
        uses: Platane/snk@v3
        with:
          github_user_name: gastonsegura2908
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake contribution grid"
          add: "output/*.svg"
